### ISSUE TITLE
CI report generated without escaped characters

### ISSUE THREAD

**Issue by Werewolfas** [hitode909/backstop-retry-failed-scenarios#50]
If selectors have quotes, for example `section[data-test="alert"]`, then `xunit.xml` generated with broken XML syntax. 
My suggestion is to escape characters on XML generation.

**Comment by hitode909** [comment]
@Werewolfas Thank you for your contribution!
 I merged #51 and I'll release next version.

**Comment by hitode909** [comment]
@Werewolfas I published 1.1.2 on npm.
- https://www.npmjs.com/package/backstop-retry-failed-scenarios
